apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
    aws_access_key_id: QVNJQTNYMk5ST0ZWTVBRTkdWNjI=
    aws_secret_access_key: SUdmSTRtdTFQdjhvaDgvMGdndUF3d3BQWGlTYXRoSVFXSm5XaXBUaw==
    aws_session_token: RndvR1pYSXZZWGR6RUZ3YURMdjE0aWV0SThScGFVd3lheUxWQVFkVjFrMjQxNGNWSlMrb005NUpmdXBEZ1h3SkxjK0Z4enVHa3ZjTDZRTnBEMnBxMFZyMjRwZFJWZWN6Qlg1STFVL0diMnJVaElBUUlTLzg4b1hxQXNTWFh3T2RFcFIrZ1plYVhVekhjUVFuOVJyYThpelpHaFR3cUNXcWhuODRDSHhyRXhLS3MyNjI4ZzRWb0xLUk4wbjFwUFp1MkJVd0Ntc3BURkxFbnc5T2dWbEo3bkI2Si9zY09mZWw2S0NFaHU3MHdPVDBkUnZzUURoWEhHTVZnenovS25MUUVUamRUbXpVcXlJUDZzNHc3TGdwc0tXOHkrK01CMUtuV2xmaC9TUmZBOU5Na01qWkpGWEF6Y3lmSmNod3lqb3JQU2lDNmVLUUJqSXRQbjA4U0FvK0cweWsyckJJV1JSYU53ME84dC9IWjZsQ1BzbEtMTTJuRTlwRUt4c2xZWHdNOVpGK3lTa1c=